name: GenoPrimer
channels:
  - anaconda
  - https://conda.anaconda.org/anaconda
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.78
  - blas=1.0=mkl
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - cryptography=3.1.1
  - cython=0.29.21
  - et_xmlfile=1.0.1
  - idna=2.10
  - intel-openmp=2021.4.0
  - jdcal=1.4.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openpyxl=3.0.5
  - openssl=1.1.1h
  - pandas=1.1.3
  - pip=20.2.4
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2020.1
  - regex=2020.10.15
  - requests=2.24.0
  - setuptools=50.3.0
  - six=1.15.0
  - sqlite=3.33.0
  - urllib3=1.25.11
  - vc=14.1
  - wheel=0.35.1
  - zlib=1.2.11
  - pip:
    - primer3-py==0.6.1
